### ISSUE TITLE
Unit Test Modules

### ISSUE THREAD

**Issue by tomopagu** [paguco/disbott#20]
We should really be unit testing I guess to make sure all the commands work.

Something like [AVA](https://github.com/sindresorhus/ava) could be cool to use

**Comment by 80cmdude** [comment]
@HumanoidAsh should take a look at this.

**Comment by tomopagu** [comment]
That would be cool, I think the way it would be work would be for disbott to join the dev server and then do commands in a test channel and expect certain results. When in test mode it will need to change https://github.com/tomopagu/disbott/blob/master/bot.js#L73 so it can do commands.

**Comment by 80cmdude** [comment]
That's probably the best way otherwise you will have to create another user dsibott_test just to test disbott. And then the cycle goes on.

**Comment by tomopagu** [comment]
Well we have got disbott-dev & Disbott Test server, I'll give this a look tomorrow as a starter and then @HumanoidAsh could expand or suggest another way.

Unit testing is very new to me so will need suggestions help here

**Comment by tomopagu** [comment]
Just to make it easier, here is the initial test file: https://github.com/tomopagu/disbott/blob/bd5852aed468bc89077b38b453c5736ed4a698d0/test.js

**Comment by tomopagu** [comment]
Closing this as a bit obsolete with the labels and us _hopefully_ doing tests as we convert the modules over
