### ISSUE TITLE
Add a dice roller command

### ISSUE THREAD

**Issue by tomopagu** [paguco/disbott#5]
Few people on the server would like to add a dice roller command for when playing dnd. It needs to be able to multiple dice configs and numbers and output results of the dice and totals, highlight crit fails/successes.

**Comment by 80cmdude** [comment]
Hey man, I made a first attempt today!!!! Its done through HTML so I am a way off of integrating it with Disbott. Got to start somewhere, i have 2 years to catch up on you.

https://github.com/80cmdude/Padawan-Project/tree/master/Dice%20Roller

**Comment by tomopagu** [comment]
Looks a good start man!

**Comment by 80cmdude** [comment]
About 60% ready to try and get it converted over but i will need a last bit of help with some stuff if that is okay!!

**Comment by tomopagu** [comment]
That's cool, ping me when you're working on it!

**Comment by 80cmdude** [comment]
Created an MVP for now will add better functionality later

**Comment by tomopagu** [comment]
If you're happy with this, I'd like to close this issue @80cmdude since #44 handles the better functionality issue.

**Comment by tomopagu** [comment]
Closing as this is done and tested, #44 will handle anything more complex

**Comment by tomopagu** [comment]
As of 96bb89ad5ffd9fb255b6dc4aeb26358bfe8bd20d we're at 100% coverage (aside from view)
