### ISSUE TITLE
Folders/Files need cleanup

### ISSUE THREAD

**Issue by tomopagu** [paguco/disbott#50]
Due to issues merging and new modules it's looking a little cluttered inside Disbott. Like we have a Giphy & Objects folders in here: https://github.com/paguco/disbott/tree/c%23/Disbott when they are repeated in Modules with a Dan Quotes & Quotes folder.

**Comment by 80cmdude** [comment]
I'll pick this up its my fault I deleted the wrong thing

**Comment by 80cmdude** [comment]
@tomopagu not gonna branch for this gonna work straight to master

**Comment by 80cmdude** [comment]
Straigh to c#master

**Comment by 80cmdude** [comment]
File Structure done

**Comment by tomopagu** [comment]
Looks good, providing all the commands still run this is fine as a test success so can close then.

**Comment by tomopagu** [comment]
Closing as all commands ran when we did testing a few days back.
